### ISSUE TITLE
How to use with Google login on Freenom?

### ISSUE THREAD

**Issue by ajh123** [Sorok-Dva/freenom-auto-renew-domains#11]
So I use a Google account to login to Freenom
I get this error when using a Google account
```
Connected to the freenoms-domains database.
Domain Checker - Freenom
Username complete
Password complete

[login] Error TimeoutError: waiting for selector `.renewalContent` failed: timeout 30000ms exceeded
    at new WaitTask (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:513:34)
    at DOMWorld.waitForSelectorInPage (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:424:26)
    at internalHandler.waitFor (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:317:29)
    at Frame.waitForSelector (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2313:33)
    at Object.login (/home/pi/services/freenom-auto-renew-domains/config/freenom.js:66:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.init (/home/pi/services/freenom-auto-renew-domains/config/freenom.js:47:7)
    at async CronJob.<anonymous> (/home/pi/services/freenom-auto-renew-domains/app.js:13:3)
Scrap finished for https://my.freenom.com/domains.php?a=renewals
[renew] Error Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:35)
    at ExecutionContext._evaluateInternal (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/home/pi/services/freenom-auto-renew-domains/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24)
```
I suspect that [freenom-auto-renew-domains](https://github.com/Sorok-Dva/freenom-auto-renew-domains) does not know how to login with Google. Or at least how I have it in my config

```
DB_NAME=freenoms-domains
CHROME_PATH=/usr/bin/chromium-browser
DISCORD_WEBHOOK_ID=*******************
DISCORD_WEBHOOK_TOKEN=**********************************************
FREENOM_LOGIN=example@gmail.com
FREENOM_PASS=my google password
FREENOM_CRONJOB="*/5 * * * *"
```

**Comment by xuantiep** [comment]
i see and understand your pain, why you not try to login as everyone else by using email and password? that is easy part to by pass google login.

**Comment by Sorok-Dva** [comment]
Hello @ajh123, I'm sorry but this tool isn't compatible with a google login, only email and password is working.
