### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by anondev-sudo** [Sorok-Dva/freenom-auto-renew-domains#27]
Hello, it stopped working

```
Connected to the freenom1-domains database.
Domain Checker - Freenom
Username complete
Password complete
connected
[renew] Error Error: net::ERR_ABORTED at https://my.freenom.com/domains.php?a=renewdomain&domain=1107348492
    at navigate (/home/container/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:194:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/home/container/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:170:21)
    at async Frame.goto (/home/container/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:583:16)
    at async Page.goto (/home/container/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1112:16)
    at async /home/container/config/freenom.js:119:11
    at async Promise.all (index 2)
    at async Object.renewFreeDomains (/home/container/config/freenom.js:98:7)
    at async Object.init (/home/container/config/freenom.js:52:7)
    at async run (/home/container/app.js:18:3)
Scrap finished for https://my.freenom.com/domains.php?a=renewals
```

It doesnt want to renew anymore

**Comment by Sorok-Dva** [comment]
Hi, Does it happens in the docker container or with pm2 ?

**Comment by anondev-sudo** [comment]
Running in docker container using pterodactyl panel

**Comment by Sorok-Dva** [comment]
I cannot reproduce, can you try in localhost ?
